hslavich_onelogin_saml:
  idp:
    entityId: 'https://sts.windows.net/809929af-2d25-45bf-9837-089eb9cfbd01/'
    singleSignOnService:
      url: 'https://login.microsoftonline.com/809929af-2d25-45bf-9837-089eb9cfbd01/saml2'
      binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
    singleLogoutService:
      url: 'https://login.microsoftonline.com/common/wsfederation?wa=wsignout1.0'
      binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
    x509cert: '%env(resolve:SAML_CERT)%'
  sp:
    entityId: '%env(resolve:BASE_URL)%/saml/metadata'
    assertionConsumerService:
      url: '%env(resolve:BASE_URL)%/saml/acs'
      binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST'
    singleLogoutService:
      url: '%env(resolve:BASE_URL)%/saml/logout'
      binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'